name: Setup Next.js App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-next-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the version of Node.js you prefer

    - name: Install bun
      run: npm install -g bun
      
    - name: Create Next.js app
      run: npx create-next-app@latest nextjs-boilerplate --src-dir --use-bun --ts --eslint --tailwind --app --import-alias "@/*"

    - name: Move Next.js app to root
      run: |
        shopt -s dotglob
        mv nextjs-boilerplate/* .
        rmdir nextjs-boilerplate

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Set up Next.js app with create-next-app'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
